# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
      ./hardware-configuration.nix
    ];


  fileSystems."/home/acmota2" =
    { device = "/dev/disk/by-uuid/78b82b4a-37ec-463b-8ac9-ac44b108a98b";
      fsType = "ext4";
    };

  swapDevices = [ { device = "/dev/disk/by-uuid/79b6eb49-e014-4870-8e91-a9ce3366ee3f"; } ];
}

