daemonize
ignore-empty-password
show-failed-attempts

# === Background ===
image=~/pictures/covao-da-ametade-cold.jpg
scaling=fill
effect-blur=7x5

# === General ===
font=JetBrainsMono
font-size=48

clock
timestr=%H:%M
datestr=%A, %d %B

# === Indicator ===
indicator
indicator-radius=140
indicator-thickness=6

# Transparent center
inside-color=00000000
inside-clear-color=00000000
inside-ver-color=00000000
inside-wrong-color=00000000

# Neon-ish ring
ring-color=33ccffee
ring-clear-color=33ccffee
ring-ver-color=00ff99ee
ring-wrong-color=ff6633ee

line-color=00000000
separator-color=00000000

# === Text styling ===
text-color=c8c8c8ff
text-clear-color=c8c8c8ff
text-ver-color=c8c8c8ff
text-wrong-color=c8c8c8ff

# Keypress highlights
key-hl-color=00ff99ee
bs-hl-color=ff6633ee

# Caps / layout
indicator-caps-lock
show-keyboard-layout
layout-text-color=c8c8c8ff

# === Extra text ===
text-caps-lock=Authenticating...
